{
  "format_version": 2,
  "sksl": {
    "entrypoint": "golden_aura_fragment_main",
    "shader": "// This SkSL shader is autogenerated by spirv-cross.\n\nfloat4 flutter_FragCoord;\n\nuniform vec2 uSize;\nuniform float uTime;\nuniform float uIntensity;\n\nvec4 fragColor;\n\nvec2 FLT_flutter_local_FlutterFragCoord()\n{\n    return flutter_FragCoord.xy;\n}\n\nvoid FLT_main()\n{\n    vec2 uv = FLT_flutter_local_FlutterFragCoord() / uSize;\n    vec2 center = vec2(0.5);\n    float distToCenter = distance(uv, center);\n    float pulse = (sin((distToCenter * 15.0) - (uTime * 8.0)) * 0.5) + 0.5;\n    vec4 goldColor = vec4(1.0, 0.800000011920928955078125, 0.20000000298023223876953125, 1.0);\n    fragColor = (goldColor * pulse) * uIntensity;\n}\n\nhalf4 main(float2 iFragCoord)\n{\n      flutter_FragCoord = float4(iFragCoord, 0, 0);\n      FLT_main();\n      return fragColor;\n}\n",
    "stage": 1,
    "uniforms": [
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 0,
        "name": "uSize",
        "rows": 2,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 1,
        "name": "uTime",
        "rows": 1,
        "type": 10
      },
      {
        "array_elements": 0,
        "bit_width": 32,
        "columns": 1,
        "location": 2,
        "name": "uIntensity",
        "rows": 1,
        "type": 10
      }
    ]
  }
}